---
- name: Example playbook
  hosts: espdev, esp_solar, pybV1.1, gkesp32
  tasks:
    - name: Raw MP Command
      command: "import time;print('hello');led.on();time.sleep(1);led.off()"
    - name: Raw MP Command Parallel
      command_nb: "led.on();time.sleep(2);led.off()"
    - name: Command Parallel
      wait: 5 
      command_pl: "print('hello1');led.on();time.sleep(2);print('hello2');led.off()"
    - name: Check conn
      wait: 2
      command: "print('Hi')"
    - name: Load Parallel 
      wait: 5
      load_pl: "sample.py"
    - name: Check conn2 
      wait: 2
      command: "print('Hi')"
